### ISSUE TITLE
d2xx: Allow re-enumeration of devices and GPIO pins

### ISSUE THREAD

**Issue by mikaelnousiainen** [periph/extra#8]
Currently the `d2xx` driver can be initialized only once and it cannot re-enumerate any new devices after first initialization. With hot-pluggable USB-devices, this makes it difficult to use the driver, as the application using the driver needs to be restarted.

Please provide a way to trigger re-enumeration of `d2xx` devices and related GPIO pins.

**Comment by maruel** [comment]
Yes that'd be cool if someone could implement it.

**Comment by maruel** [comment]
Moved to https://github.com/periph/host/issues/4

**Comment by maruel** [comment]
FYI, periph.io/x/host/v3@v3.7.0 has native FTDI support so no magic is needed anymore.
